#!/usr/bin/env bash
# Deploy Nexus to a public VPS with automatic HTTPS (Let's Encrypt via Caddy).
#
# Prerequisites:
#   1. A VPS (DigitalOcean, Hetzner, Linode, AWS EC2, etc.) with Ubuntu 22.04+
#   2. A domain name (e.g. nexus-ai.com) with DNS pointing to this server's IP
#   3. Docker + Docker Compose installed on the server
#
# Usage (on your VPS):
#   git clone https://github.com/ShubhamRSY/voice-agents.git
#   cd voice-agents
#   bash scripts/deploy-public.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/config/environment/.env"
COMPOSE_FILE="$ROOT/deploy/docker/docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}→${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
error() { echo -e "${RED}✗${NC} $*" >&2; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { error "$1 is required but not installed."; exit 1; }
}

generate_secret() {
  openssl rand -hex 32
}

generate_fernet() {
  python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || docker run --rm python:3.12-slim python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
}

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         Nexus — Public Production Deployment             ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

require_cmd docker
require_cmd openssl

if ! docker compose version >/dev/null 2>&1; then
  error "Docker Compose v2 is required (docker compose)."
  exit 1
fi

# ── Collect domain ────────────────────────────────────────────
if [[ -n "${DOMAIN:-}" ]]; then
  PUBLIC_DOMAIN="$DOMAIN"
else
  echo "Enter your public domain (e.g. nexus.example.com):"
  read -r PUBLIC_DOMAIN
fi

PUBLIC_DOMAIN="${PUBLIC_DOMAIN#https://}"
PUBLIC_DOMAIN="${PUBLIC_DOMAIN#http://}"
PUBLIC_DOMAIN="${PUBLIC_DOMAIN%%/*}"

if [[ -z "$PUBLIC_DOMAIN" || "$PUBLIC_DOMAIN" == ":80" ]]; then
  error "A real domain is required for public HTTPS deployment."
  exit 1
fi

# ── Optional API key ─────────────────────────────────────────
if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo ""
  echo "OpenAI API key (press Enter to skip — mock LLM will be used):"
  read -r OPENAI_API_KEY
fi

# ── Generate secrets ─────────────────────────────────────────
info "Generating production secrets..."
JWT_SECRET_VAL="$(generate_secret)"
POSTGRES_PASS="$(generate_secret | head -c 32)"
FERNET_KEY="$(generate_fernet)"
SETTINGS_TOKEN="$(generate_secret)"

# ── Write .env ────────────────────────────────────────────────
mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-public.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Public domain: $PUBLIC_DOMAIN

# ── LLM ───────────────────────────────────────────────────────
OPENAI_API_KEY=${OPENAI_API_KEY:-}
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4o-mini

# ── Telephony (optional) ──────────────────────────────────────
TWILIO_WEBHOOK_BASE_URL=https://${PUBLIC_DOMAIN}

# ── Database & cache (managed by docker-compose) ──────────────
DATABASE_URL=postgresql://nexus:${POSTGRES_PASS}@postgres:5432/nexus
REDIS_URL=redis://redis:6379/0
CHROMA_PERSIST_DIR=./data/chroma

# ── Security (auto-generated) ─────────────────────────────────
JWT_SECRET=${JWT_SECRET_VAL}
INTEGRATIONS_ENCRYPTION_KEY=${FERNET_KEY}
SETTINGS_ADMIN_TOKEN=${SETTINGS_TOKEN}
AUTH_REQUIRED=true
DEMO_MODE=false
APP_ENV=production

# ── Public domain ─────────────────────────────────────────────
DOMAIN=${PUBLIC_DOMAIN}
CORS_ORIGINS=https://${PUBLIC_DOMAIN}
POSTGRES_PASSWORD=${POSTGRES_PASS}

# ── App ───────────────────────────────────────────────────────
APP_HOST=0.0.0.0
APP_PORT=8000
LOG_LEVEL=INFO
LOG_SINK=stdout
RATE_LIMIT_RPM=120
EOF

chmod 600 "$ENV_FILE"
info "Wrote $ENV_FILE"

# ── DNS reminder ──────────────────────────────────────────────
echo ""
warn "Before continuing, make sure DNS is configured:"
if [[ "$PUBLIC_DOMAIN" == *".duckdns.org" ]]; then
  echo "  DuckDNS: set ${PUBLIC_DOMAIN} → $(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo '<this-server-public-IP>')"
  echo "  Verify:  ping ${PUBLIC_DOMAIN}"
else
  echo "  Type: A"
  echo "  Name: ${PUBLIC_DOMAIN%%.*} (or @ for apex)"
  echo "  Value: $(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo '<your-server-public-IP>')"
fi
# Non-interactive deploy (skip DNS prompt)
if [[ -n "${NONINTERACTIVE:-}" || ! -t 0 ]]; then
  info "Non-interactive mode — skipping DNS confirmation"
else
  echo ""
  echo "Press Enter when DNS is pointing to this server (or Ctrl+C to abort)..."
  read -r _
fi

# ── Deploy ────────────────────────────────────────────────────
info "Building and starting production stack..."
cd "$ROOT"
docker compose -f "$COMPOSE_FILE" up -d --build

echo ""
info "Waiting for health check..."
for i in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:8000/api/v1/health" >/dev/null 2>&1 \
     || docker compose -f "$COMPOSE_FILE" exec -T nexus python -c \
        "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/v1/health')" 2>/dev/null; then
    break
  fi
  sleep 2
done

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                    Deployment complete                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Website:  https://${PUBLIC_DOMAIN}"
echo "  Health:   https://${PUBLIC_DOMAIN}/api/v1/health"
echo ""
echo "  Next steps:"
echo "  1. Open https://${PUBLIC_DOMAIN} in your browser"
echo "  2. Register your first admin: POST /api/v1/auth/register"
echo "  3. Save your secrets from config/environment/.env (JWT, DB password)"
echo ""
warn "Caddy may take 1–2 minutes to provision the Let's Encrypt certificate."
echo ""
